config/routes.rb
Rails.application.routes.draw do

  post 'subscribtion_list/subscribe' => 'subscribtion_list#subscribe'
  
  match '/get-gstarcad-2016',  to: 'subscribtion_list#landingPage', via: 'get'
  match '/get-cadprofi-mechanical',  to: 'subscribtion_list#landingPageMech', via: 'get'
  match '/get-cadprofi-hvac-and-piping',  to: 'subscribtion_list#landingPageHVAC', via: 'get'

  #Page Errors
  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_server_error'

  scope "(:locale)", locale: /uk|au|nz|it/ do
    resources :contact_us_messages
    resources :support_messages    
    resources :forums do
      resources :topics do
        resources :topic_answers
      end
    end
    
    #devise_for :admins
    devise_for :users

    root 'pages#index'

    match '/professional-cad',  to: 'pages#proCad', via: 'get'
    match '/technical-applications',  to: 'pages#techApps', via: 'get'
    match '/about-us',  to: 'pages#aboutUs', via: 'get'
    match '/contact-us',  to: 'contact_us_messages#new', via: 'get'
    match '/technical-applications/cadprofi-mechanical',  to: 'pages#cadprofiMechanical', via: 'get'
    match '/technical-applications/cadprofi-architectural',  to: 'pages#cadprofiArchitectural', via: 'get'
    match '/technical-applications/cadprofi-hvac-and-piping',  to: 'pages#cadprofiHVAC', via: 'get'
    match '/technical-applications/cadprofi-electrical',  to: 'pages#cadprofiElectrical', via: 'get'
    match '/privacy-policy',  to: 'pages#privacyPolicy', via: 'get'
    match '/site-map',  to: 'pages#siteMap', via: 'get'
    match '/users/downloads',  to: 'pages#downloadArea', via: 'get'
    match '/users/dashboard',  to: 'pages#userDashboard', via: 'get'
    match '/posts',  to: 'posts#index', via: 'get'
    match '/administrator/posts/new',  to: 'posts#new', via: 'get'
    match '/posts/create',  to: 'posts#create', via: 'post'
    match '/administrator/dashboard',  to: 'admin_dashboard#index', via: 'get'
    match '/administrator/posts',  to: 'admin_dashboard#posts', via: 'get'
    match '/administrator/users',  to: 'admin_dashboard#users', via: 'get'
    match '/administrator/forums',  to: 'admin_dashboard#forums', via: 'get'
    match '/administrator/posts/edit',  to: 'posts#edit', via: 'get'
    match '/administrator/posts/update',  to: 'posts#update', via: 'post'
    match '/posts/:id',  to: 'posts#show', via: 'get', as: :slug
    match '/administrator/posts/destroy',  to: 'posts#destroy', via: 'delete'
    match '/administrator/users/:id',  to: 'users#destroy', via: 'delete', as: :administrator_user_destroy
    match '/administrator/users/:id',  to: 'users#edit', via: 'get', as: :administrator_user_edit
    match '/administrator/users/:id',  to: 'users#update', via: 'patch', as: :administrator_user_update
    match '/users/downloads/cad-profi',  to: 'download#downloadCADprofi', via: 'get'
    match '/users/downloads/gstar-cad-64',  to: 'download#downloadGCAD64', via: 'get'
    match '/users/downloads/gstar-cad-32',  to: 'download#downloadGCAD32', via: 'get'
    match '/users/downloads/gstar-cad-pdf',  to: 'download#downloadGCADPDF', via: 'get'

    match '/categories',  to: 'categories#index', via: 'get'
    match '/categories/new',  to: 'categories#new', via: 'get'
    match '/categories/post',  to: 'categories#create', via: 'post'
  end

end

app/controllers/subscribtion_list_controller.rb
class SubscribtionListController < ApplicationController

  after_filter :flash_to_headers

  def index
  end

  def subscribe
    #Email address
    @email = params[:email][:address]
    @name = params[:email][:firstname]
    @surname = params[:email][:lastname]
  	@list_id = Rails.application.secrets.mailchimp_list_id
    gb = Gibbon::Request.new(api_key: Rails.application.secrets.mailchimp_api_key)

    #Generate password
    @generated_password = Devise.friendly_token.first(8)
    
    #Create a user, if it doesn't exist
    if User.exists?({email: @email})
      flash[:error] = "The email already exist"
    else
      @user = User.create!(:email => @email, :password => @generated_password, :name => @name, :surname => @surname)

      #Send a message with the email address and the password generated
      WelcomeSubscribeMailer.your_password(@email, @name, @generated_password).deliver

      gb.lists(@list_id).members.create(body: {
      	email_address: params[:email][:address], 
      	status: "subscribed", 
      	merge_fields: {
      		FNAME: params[:email][:firstname], 
      		LNAME: params[:email][:lastname]
      	}
      })
    end

  end

  def landingPage
    render layout: "landing"
  end

  def landingPageMech
    render layout: "landing"
  end

  def landingPageHVAC
    render layout: "landing"
  end

  def flash_to_headers
    return unless request.xhr?
    response.headers['X-Message'] = flash[:error] unless flash[:error].blank?
    flash.discard
  end
end

app/helpers/subscribtion_list_helper.rb
module SubscribtionListHelper
end

app/views/subscribtion_list/index.html.erb
<h2>Almost there...</h2>
<div class="tagline">Please fill the form below.</div>
<%= form_tag(subscribtion_list_subscribe_path, id: "subscribe", remote: "true") do %>
   <%= email_field(:email, :address, {id: "mailEmail", placeholder: "Email Address"}) %>
   <%= text_field(:email, :firstname, {id: "mailName", placeholder: "First Name"}) %>
   <%= text_field(:email, :lastname, {id: "mailSurname", placeholder: "Last Name"}) %>
   <%= submit_tag("Sign me up & get the discount!", {class: "btn green send"})  %>
<% end %>

app/views/subscribtion_list/landingPage.html.erb
	<!-- Social Media SDKs -->
	<%= render :partial => '/shared/socialmediasdks' %> 
	<!-- Social Media SDKs ends -->

	<div class="loader">
	<%= image_tag("logo.png") %>
	<span>Loading ...</span>
	</div>

	<div id="leftSection">
		<div class="positioned">
			<!--
			<div class="phone">
				<img src="http://assets.cad2b.co.uk/landing/images/phone.png">
				<span>0808 189 1390</span>
			</div>-->

			<%= link_to image_tag("gstarlogo-2016.png", class: "logo-gstar", alt: "GstarCAD 2016 - New features"), professional_cad_path %>

			<h1>The new GstarCAD 2016 is here.</h1>
			<p class='tagline'>Easy to use, low cost CAD program that will increase your productivity and improve the quality of your design. GstarCAD 2016 is simple, flawless CAD platform created specifically for more efficiency</p>

			<h2>Sign up to download free trial and get 10% discount</h2>

			<%= flash[:error] %>

			<%= form_tag(subscribtion_list_subscribe_path, id: "subscribe", remote: "true") do %>
				<div class="field"><%= email_field(:email, :address, {id: "mailEmail", placeholder: "Email Address"}) %></div>
			   	<div class="field"><%= text_field(:email, :firstname, {id: "mailName", placeholder: "First Name"}) %></div>
			   	<div class="field"><%= text_field(:email, :lastname, {id: "mailSurname", placeholder: "Last Name"}) %></div>
			   <%= submit_tag("Sign me up & get the discount!", {class: "btn green send"})  %>
			<% end %>

			<div class="share_buttons centralized">
	          <a class="twitter-share-button"
	            href="https://twitter.com/intent/tweet?text=Try for free GstarCAD 2016 and get 10%25 discount now!&url=http://cad2b.co.uk/get-gstarcad-2016&via=cad2b">
	          Tweet</a>
	          <a href="https://www.facebook.com/dialog/feed?app_id=147982825558188&link=http://cad2b.co.uk/&name=Try for free GstarCAD 2016 and get 10% discount now!&description=Easy to use, low cost CAD program that will increase your productivity and improve the quality of your design. GstarCAD 2016 is simple, flawless CAD platform created specifically for more efficiency&caption=By CAD2B&redirect_uri=http://cad2b.co.uk/get-gstarcad-2016" target="_blank" class="fb-share"><%= image_tag('fb-icon.png') %> Share</a>
			</div>

		</div>
		<span class="bg_image"></span>
	</div>
	<div id="rightSection">
		<div class="positioned">

			<div id="versions" class="panel">
				<a href="http://www.cad2b.co.uk/uk/professional-cad#prices"><span class="starts_from">LT, Standard or Professional, choose the best for you, starting from &pound;189</span></a>
		      	<div class="package one">
			        <h4>LT</h4>
			        <ul>
			          <li>All the 2D Features and Performances you need to start working</li>
			        </ul>
		      	</div>
		      	<div class="package two">
		        	<h4>Standard</h4>
			        <ul>
			          <li>LT Features</li>
			          <li>Express Tools</li>
			          <li>Application Support</li>
			        </ul>
		      	</div>
		      	<div class="package three">
			        <h4>Professional</h4>
			        <ul>
			          <li>Standard Features</li>
			          <li>ACIS 3D Modeling</li>
			          <li>Dynamic Block Editor</li>
			        </ul>
		      	</div>
			</div>

			<h2>What's new?</h2>
			<div class="features_container">
				<div class="arrow_controls">
					<a href="#" class="prev control"></a>
					<a href="#" class="next control"></a>
				</div>
				<div class="features panel">
					<ul data-state="enabled">
						<li id='1' class='active'>
							<div class="video">
								<iframe id="video1" width="100%" height="100%" src="https://www.youtube.com/embed/spUH0JfKhdo?enablejsapi=1" frameborder="0" allowfullscreen></iframe>
							</div>
							<h3>Multifunctional Grip and Invert Fillet</h3>
							<p>Polyline objects in GstarCAD 2016 now support multifunctional options. The available functions ( Stretch, Add Vertex and Convert to Arc) can be seen by hovering over a grip Invert Fillet has a very wide range of usage particularly in construction and furniture industry. The Fillet command now offers a new option called Invert. You can easy create a reverse fillet without performing circle, arc trim command.</p>
						</li>
						<li id='2'>
							<div class="video">
								<iframe id="video2" width="100%" height="100%" src="https://www.youtube.com/embed/xjOoV_Fgkj0" frameborder="0" allowfullscreen></iframe>
							</div>
							<h3>New Dynamic Input</h3>
							<p>The new dynamic input displays all options of a command and could select them in different methods. Users no longer need the command line either floated or docked, gaining more workspace to get wider viewing of the drawing</p>
						</li>
						<li id='3'>
							<div class="video">
								<iframe id="video3" width="100%" height="100%" src="https://www.youtube.com/embed/lWgsXSn4Gzc" frameborder="0" allowfullscreen></iframe>
							</div>
							<h3>Implementation</h3>
							<p>This new version implements highly requested features regarding compatibility and 3D functionality. GstarCAD 2016 has implemented the full DGN files support and related commands. Regarding to 3D functionality implementation, SOLIDEDIT comes with related 3D solid editing command options like Imprint Edges, Color and Copy Edges. And also within Body editing you could find: Clean, Separate Solids, Shell and Check Options, that allow users an advance 3d solid edition.</p>
						</li>
						<li id='4'>
							<div class="video">
								<iframe id="video4" width="100%" height="100%" src="https://www.youtube.com/embed/49rQWUkqLfA" frameborder="0" allowfullscreen></iframe>
							</div>
							<h3>New Additions</h3>
							<p>GstarCAD 2016 offers two new additions regarding to object snap and plot and publish control. Now within drafting settings dialog box, under object snap tab, you can find a new added option called Distance from Endpoint. This option allows a certain distance from any end point of objects like line, arc, spline, pline and many other lines. The divide segments option allows snap the divided segment points of objects like line, arc, spline and many other lines The new Options TAB “Plot and Publish” is a shortcut access that helps users to control options related to plotting and publishing.</p>
						</li>
						<li id='5'>
							<div class="video">
								<iframe id="video5" width="100%" height="100%" src="https://www.youtube.com/embed/pEPURu_HxGM" frameborder="0" allowfullscreen></iframe>
							</div>
							<h3>Performance Optimization</h3>
							<p>The performance is a key point on every GstarCAD version, therefore Gstarsoft is making great effort on performance optimization continuously. GstarCAD 2016 unleashes power speed performance, when opening drawings, copy or moving objects, or even undo actions over 20% faster than before, wich means users entire drawing efficiency can be improved more than 10% if compare with previous versions.</p>
						</li>
					</ul>
					<!--<img src="http://assets.cad2b.co.uk/landing/images/gstarcad-2016-user-interface.gif">-->

					<a href="http://cad2b.co.uk/uk/professional-cad#features" class="btn green more">See more functions</a>
					<a href="http://cad2b.co.uk/uk/professional-cad#overview" class="promo">Watch the promo video</a>
				</div>
			</div>
			<p class="info">CAD2B is a provider of CAD design software and DWG based applications.</p>
			<a href="http://www.cad2b.co.uk"><%= image_tag "logo-gray.png", class: "logo", alt: "Logo CAD2B" %></a>
		</div>
	</div>

app/views/subscribtion_list/landingPageHVAC.html.erb
	<!-- Social Media SDKs -->
	<%= render :partial => '/shared/socialmediasdks' %> 
	<!-- Social Media SDKs ends -->

	<div class="loader">
	<%= image_tag("logo.png") %>
	<span>Loading ...</span>
	</div>

	<div id="leftSection" class="mech_landing">
		<div class="positioned">
			<!--
			<div class="phone">
				<img src="http://assets.cad2b.co.uk/landing/images/phone.png">
				<span>0808 189 1390</span>
			</div>-->

			<%= link_to image_tag("cadprofi/cadprofi-hvac-piping-logo.jpg", class: "logo-gstar", alt: "GstarCAD 2016 - New features"), professional_cad_path %>

			<h1>CADprofi HVAC &amp; Piping</h1>
			<p class='tagline'>Design fast and efficiently. Parametric CAD-application for design technical building equipment. All installation kinds will be supported, i.e. heating, ventilation, air conditioning, piping and ducting.<br>Thanks to many features available in the CADprofi program you will perform your job much faster.</p>

			<h2>Sign up to download free trial</h2>

			<%= flash[:error] %>

			<%= form_tag(subscribtion_list_subscribe_path, id: "subscribe", remote: "true") do %>
				<div class="field"><%= email_field(:email, :address, {id: "mailEmail", placeholder: "Email Address"}) %></div>
			   	<div class="field"><%= text_field(:email, :firstname, {id: "mailName", placeholder: "First Name"}) %></div>
			   	<div class="field"><%= text_field(:email, :lastname, {id: "mailSurname", placeholder: "Last Name"}) %></div>
			   <%= hidden_field_tag :iscadprofipage %>
			   <%= submit_tag("Sign me up!", {class: "btn green send"})  %>
			<% end %>

			<div class="share_buttons centralized">
	          <a class="twitter-share-button"
	            href="https://twitter.com/intent/tweet?text=Try for free CADprofi HVAC&Piping now!&url=http://cad2b.co.uk/get-cadprofi-hvac-and-piping&via=cad2b">
	          Tweet</a>
	          <a href="https://www.facebook.com/dialog/feed?app_id=147982825558188&link=http://cad2b.co.uk/&name=Try for free CADprofi HVAC&Piping now!&description=Parametric CAD-application for design technical building equipment. All installation kinds will be supported, i.e. heating, ventilation, air conditioning, piping and ducting.&caption=By CAD2B&redirect_uri=http://cad2b.co.uk/get-cadprofi-hvac-and-piping" target="_blank" class="fb-share"><%= image_tag('fb-icon.png') %> Share</a>
			</div>

		</div>
		<span class="bg_image"></span>
	</div>
	<div id="rightSection">
		<div class="positioned">

			<div id="versions" class="panel">
				<a href="http://cad2b.co.uk/uk/technical-applications/cadprofi-hvac-and-pipng#prices"><span class="starts_from">For a small price you can easily draw and edit projects using advanced commands and the largest library of symbols and objects. Starting from &pound;70</span></a>
		      	<div class="package one">
			        <h4>CP-Symbols HVAV &amp; Piping</h4>
			        <ul>
			          <li>A set of CAD symbols from various industries.</li>
			          <li>Possibility to buy a single library, whole branch series or a whole set (Suite).</li>
			          <li>Compatibility with the latest CAD programs.</li>
			          <li>Possibility to create specifications.</li>
			        </ul>
		      	</div>
		      	<div class="package two">
		        	<h4>CADprofi HVAC &amp; Piping</h4>
			        <ul>
			          <li>A comprehensive program that help in designing.</li>
			          <li>Acess to libraries of well-known manufacturers.</li>
			          <li>Extended content of symbols libraries and parametrical objects from many standards.</li>
			          <li>Advanced editor for schemes and diagrams.</li>
			          <li>Possibility to extend the databases on your own.</li>
			          <li>Tools for full description and projects detailing.</li>
			          <li>Compatibility with the latest CAD programs.</li>
			          <li>Extended specification creator.</li>
			          <li>Additional edition commands.</li>
			        </ul>
		      	</div>
			</div>

			<h2>Featured videos</h2>
			<div class="features_container">
				<div class="arrow_controls">
					<a href="#" class="prev control"></a>
					<a href="#" class="next control"></a>
				</div>
				<div class="features panel">
					<ul data-state="enabled">
						<li id='1' class='active'>
							<div class="video">
								<iframe id="video1" width="100%" height="100%" src="https://www.youtube.com/embed/OzmpNV2caqg?enablejsapi=1" frameborder="0" allowfullscreen></iframe>
							</div>
							<h3>Symbols</h3>
							<p>User is able to find in the program all symbols that are needed in the edition of schemes. During the insertion of symbols, user can specify all main techical parameters, wich will be later included when creating specification.</p>
						</li>
						<li id='2'>
							<div class="video">
								<iframe id="video2" width="100%" height="100%" src="https://www.youtube.com/embed/GnhEvhTCy1s" frameborder="0" allowfullscreen></iframe>
							</div>
							<h3>Lines</h3>
							<p>CADprofi allows to simultaneously draw multiple schematic lines. There are many types of lines available in the program. User can also define additional types of lines or installations</p>
						</li>
						<li id='3'>
							<div class="video">
								<iframe id="video3" width="100%" height="100%" src="https://www.youtube.com/embed/tTwD1NPhv-w" frameborder="0" allowfullscreen></iframe>
							</div>
							<h3>Schemes</h3>
							<p>In the CADprofi HVAC&amp;Piping there are already prepared fragments of schemes. USer can also define schemes by themeselves, thanks to wich it will be possible to use them in next projects</p>
						</li>
						<li id='4'>
							<div class="video">
								<iframe id="video4" width="100%" height="100%" src="https://www.youtube.com/embed/tzKhwN3210A" frameborder="0" allowfullscreen></iframe>
							</div>
							<h3>Pipes</h3>
							<p>The “2D Pipes- plan” command allows to insert to the drawings single fittings and lines. It is possible to specify all dimension of inserted elements or select it from the database of normalized sizes of from the databases or manufactures catalogs.</p>
						</li>
						<li id='5'>
							<div class="video">
								<iframe id="video5" width="100%" height="100%" src="https://www.youtube.com/embed/MwZ9RkMsCfg" frameborder="0" allowfullscreen></iframe>
							</div>
							<h3>Air Conditioning</h3>
							<p>CADprofi HVAC&amp;Piping is used to draw ventilation ducts and fittings.</p>
						</li>
					</ul>
					<!--<img src="http://assets.cad2b.co.uk/landing/images/gstarcad-2016-user-interface.gif">-->
					<a href="http://cad2b.co.uk/uk/technical-applications/cadprofi-hvac-and-piping#overview" class="btn green more">See more functions</a>
				</div>
			</div>
			<p class="info">CAD2B is a provider of CAD design software and DWG based applications.</p>
			<a href="http://www.cad2b.co.uk"><%= image_tag "logo-gray.png", class: "logo", alt: "Logo CAD2B" %></a>
		</div>
	</div>

app/views/subscribtion_list/landingPageMech.html.erb
	<!-- Social Media SDKs -->
	<%= render :partial => '/shared/socialmediasdks' %> 
	<!-- Social Media SDKs ends -->

	<div class="loader">
	<%= image_tag("logo.png") %>
	<span>Loading ...</span>
	</div>

	<div id="leftSection" class="mech_landing">
		<div class="positioned">
			<!--
			<div class="phone">
				<img src="http://assets.cad2b.co.uk/landing/images/phone.png">
				<span>0808 189 1390</span>
			</div>-->

			<%= link_to image_tag("cadprofi/cadprofi-mechanical-logo.jpg", class: "logo-gstar", alt: "GstarCAD 2016 - New features"), professional_cad_path %>

			<h1>CADprofi Mechanical</h1>
			<p class='tagline'>Design fast and efficiently. Parametric CAD-application facilitating the 2D design of mechanical and engineering projects. Thanks to many features available in the CADprofi program you will perform your job much faster.</p>

			<h2>Sign up to download free trial</h2>

			<%= flash[:error] %>

			<%= form_tag(subscribtion_list_subscribe_path, id: "subscribe", remote: "true") do %>
				<div class="field"><%= email_field(:email, :address, {id: "mailEmail", placeholder: "Email Address"}) %></div>
			   	<div class="field"><%= text_field(:email, :firstname, {id: "mailName", placeholder: "First Name"}) %></div>
			   	<div class="field"><%= text_field(:email, :lastname, {id: "mailSurname", placeholder: "Last Name"}) %></div>
			   <%= hidden_field_tag :iscadprofipage %>
			   <%= submit_tag("Sign me up!", {class: "btn green send"})  %>
			<% end %>

			<div class="share_buttons centralized">
	          <a class="twitter-share-button"
	            href="https://twitter.com/intent/tweet?text=Try for free CADprofi Mechanical now!&url=http://cad2b.co.uk/get-cadprofi-mechanical&via=cad2b">
	          Tweet</a>
	          <a href="https://www.facebook.com/dialog/feed?app_id=147982825558188&link=http://cad2b.co.uk/&name=Try for free CADprofi Mechanical now!&description=Parametric CAD-application facilitating the 2D design of mechanical and engineering projects.&caption=By CAD2B&redirect_uri=http://cad2b.co.uk/get-cadprofi-mechanical" target="_blank" class="fb-share"><%= image_tag('fb-icon.png') %> Share</a>
			</div>

		</div>
		<span class="bg_image"></span>
	</div>
	<div id="rightSection">
		<div class="positioned">

			<div id="versions" class="panel">
				<a href="http://cad2b.co.uk/uk/technical-applications/cadprofi-mechanical#prices"><span class="starts_from">For a small price you can easily draw and edit projects using advanced commands and the largest library of symbols and objects. Starting from &pound;70</span></a>
				<p class="product_description">The Mechanical module is equipped with an extensive set of standardized parts, steel fittings and other steel products, based on local and international standards. An exceptional diagram and blueprint editor vastly facilitates the creation of drawings of plumbing and pneumatic installations.</p>
		      	<div class="package one">
			        <h4>CP-Symbols Mechanical</h4>
			        <ul>
			          <li>Library of standardized parts and couplers</li>
			          <li>Library of steel shapes and profiles</li>
			          <li>Library of mechanical marks</li>
			          <li>Library of pneumatics and hydraulics symbols</li>
			          <li>Flowcharts and diagrams</li>
			          <li>Multilingual user interface</li>
			          <li>Creating bill of materials and describing symbols</li>
			          <li>Free updates for one year - subscription</li>
			        </ul>
		      	</div>
		      	<div class="package two">
		        	<h4>CADprofi Mechanical</h4>
			        <ul>
			          <li>Data management and enchanced specification creator</li>
			          <li>Extended library of standardized parts and couplers</li>
			          <li>Extended library of steel shapes and profiles</li>
			          <li>Designing with use of Parametrical Technology</li>
			          <li>Automatic design thanks to „One-click” technology</li>
			          <li>Creating mechanical and construction projects</li>
			          <li>Designing apparatus and heat exchangers</li>
			          <li>Designing advanced pneumatic and hydraulic systems</li>
			          <li>You can add additional libraries and databases on your own</li>
			          <li>Tools for full description and projects detailing</li>
			          <li>Additional edition commands</li>
			          <li>Access to the manufacturers libraries</li>
			          <li>Additional modules for better coordination between branches</li>
			        </ul>
		      	</div>
			</div>

			<h2>Featured videos</h2>
			<div class="features_container">
				<div class="arrow_controls">
					<a href="#" class="prev control"></a>
					<a href="#" class="next control"></a>
				</div>
				<div class="features panel">
					<ul data-state="enabled">
						<li id='1' class='active'>
							<div class="video">
								<iframe id="video1" width="100%" height="100%" src="https://www.youtube.com/embed/pnisvsUe74M?enablejsapi=1" frameborder="0" allowfullscreen></iframe>
							</div>
							<h3>Standardized Parts</h3>
							<p>Standardized parts: bolts, screws, washers, nuts, joints, rivets, studs, openings, rebates, wedges, pivots, pins, bearings, grease nipples, and many more.</p>
						</li>
						<li id='2'>
							<div class="video">
								<iframe id="video2" width="100%" height="100%" src="https://www.youtube.com/embed/PbZ3aFwdFF8" frameborder="0" allowfullscreen></iframe>
							</div>
							<h3>Welds and descriptions</h3>
							<p>Welds and descriptions</p>
						</li>
						<li id='3'>
							<div class="video">
								<iframe id="video3" width="100%" height="100%" src="https://www.youtube.com/embed/484_ZD2o5sc" frameborder="0" allowfullscreen></iframe>
							</div>
							<h3>Steel Shapes</h3>
							<p>Steel profiles: L­bars, tapered­channel bars, flat bars, box sections, rods, pipes, and more.</p>
						</li>
						<li id='4'>
							<div class="video">
								<iframe id="video4" width="100%" height="100%" src="https://www.youtube.com/embed/UFSknFIm9CA" frameborder="0" allowfullscreen></iframe>
							</div>
							<h3>Casing and end caps</h3>
							<p>Casings and end caps, pipes, U­bends, tees, reducers, etc.</p>
						</li>
						<li id='5'>
							<div class="video">
								<iframe id="video5" width="100%" height="100%" src="https://www.youtube.com/embed/yV45Y3RNUx4" frameborder="0" allowfullscreen></iframe>
							</div>
							<h3>Diagrams and pneumatics</h3>
							<p>Editor for diagrams of pneumatic and plumbing systems.</p>
						</li>
					</ul>
					<!--<img src="http://assets.cad2b.co.uk/landing/images/gstarcad-2016-user-interface.gif">-->
					<a href="http://cad2b.co.uk/uk/technical-applications/cadprofi-mechanical#overview" class="btn green more">See more functions</a>
				</div>
			</div>
			<p class="info">CAD2B is a provider of CAD design software and DWG based applications.</p>
			<a href="http://www.cad2b.co.uk"><%= image_tag "logo-gray.png", class: "logo", alt: "Logo CAD2B" %></a>
		</div>
	</div>