config/routes.rb
Rails.application.routes.draw do

  post 'subscribtion_list/subscribe' => 'subscribtion_list#subscribe'
  
  match '/get-gstarcad-2016',  to: 'subscribtion_list#landingPage', via: 'get'
  match '/get-cadprofi-mechanical',  to: 'subscribtion_list#landingPageMech', via: 'get'
  match '/get-cadprofi-hvac-and-piping',  to: 'subscribtion_list#landingPageHVAC', via: 'get'

  #Page Errors
  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_server_error'

  scope "(:locale)", locale: /uk|au|nz|it/ do
    resources :contact_us_messages
    resources :support_messages    
    resources :forums do
      resources :topics do
        resources :topic_answers
      end
    end
    
    #devise_for :admins
    devise_for :users

    root 'pages#index'

    match '/professional-cad',  to: 'pages#proCad', via: 'get'
    match '/technical-applications',  to: 'pages#techApps', via: 'get'
    match '/about-us',  to: 'pages#aboutUs', via: 'get'
    match '/contact-us',  to: 'contact_us_messages#new', via: 'get'
    match '/technical-applications/cadprofi-mechanical',  to: 'pages#cadprofiMechanical', via: 'get'
    match '/technical-applications/cadprofi-architectural',  to: 'pages#cadprofiArchitectural', via: 'get'
    match '/technical-applications/cadprofi-hvac-and-piping',  to: 'pages#cadprofiHVAC', via: 'get'
    match '/technical-applications/cadprofi-electrical',  to: 'pages#cadprofiElectrical', via: 'get'
    match '/privacy-policy',  to: 'pages#privacyPolicy', via: 'get'
    match '/site-map',  to: 'pages#siteMap', via: 'get'
    match '/users/downloads',  to: 'pages#downloadArea', via: 'get'
    match '/users/dashboard',  to: 'pages#userDashboard', via: 'get'
    match '/posts',  to: 'posts#index', via: 'get'
    match '/administrator/posts/new',  to: 'posts#new', via: 'get'
    match '/posts/create',  to: 'posts#create', via: 'post'
    match '/administrator/dashboard',  to: 'admin_dashboard#index', via: 'get'
    match '/administrator/posts',  to: 'admin_dashboard#posts', via: 'get'
    match '/administrator/users',  to: 'admin_dashboard#users', via: 'get'
    match '/administrator/forums',  to: 'admin_dashboard#forums', via: 'get'
    match '/administrator/posts/edit',  to: 'posts#edit', via: 'get'
    match '/administrator/posts/update',  to: 'posts#update', via: 'post'
    match '/posts/:id',  to: 'posts#show', via: 'get', as: :slug
    match '/administrator/posts/destroy',  to: 'posts#destroy', via: 'delete'
    match '/administrator/users/:id',  to: 'users#destroy', via: 'delete', as: :administrator_user_destroy
    match '/administrator/users/:id',  to: 'users#edit', via: 'get', as: :administrator_user_edit
    match '/administrator/users/:id',  to: 'users#update', via: 'patch', as: :administrator_user_update
    match '/users/downloads/cad-profi',  to: 'download#downloadCADprofi', via: 'get'
    match '/users/downloads/gstar-cad-64',  to: 'download#downloadGCAD64', via: 'get'
    match '/users/downloads/gstar-cad-32',  to: 'download#downloadGCAD32', via: 'get'
    match '/users/downloads/gstar-cad-pdf',  to: 'download#downloadGCADPDF', via: 'get'

    match '/categories',  to: 'categories#index', via: 'get'
    match '/categories/new',  to: 'categories#new', via: 'get'
    match '/categories/post',  to: 'categories#create', via: 'post'
  end

end

app/controllers/admin_dashboard_controller.rb
class AdminDashboardController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :authenticate_user_role

  layout "admin"

  def index
  	@posts = Post.all.order('created_at DESC')
  	@users = User.where(role_id: 1).order('created_at DESC')
    @topics = Topic.all.order('created_at DESC')
  end

  def posts
  	@posts = Post.all.order('created_at DESC')
  end

  def users
  	@users = User.all.order('created_at DESC')
    attributes_to_include = %w(id name surname email country phone created_at)
    respond_to do |format|
      format.html
      format.csv { send_data @users.to_csv(attributes_to_include), filename: "cad2b-users-#{Time.now.strftime("%d%m%Y%H%M%S")}.csv" }
      format.xls {
        response.header['Content-Disposition'] = "attachment; filename=\"cad2b-users-#{Time.now.strftime("%d%m%Y%H%M%S")}.xls\""
      }
    end
  end

  def forums
    @forums = Forum.all.order('created_at DESC')
  end

  private
    def authenticate_user_role
      if current_user.role_id != 4 #Admin
        redirect_to users_dashboard_path
      end
    end
  
end

app/helpers/admin_dashboard_helper.rb
module AdminDashboardHelper
end

app/views/admin_dashboard/forums.html.erb
<div id="adminPosts">
	<div class="centralized">
		<h2>Showing all forums</h2>
		<%= link_to "Post a forum", new_forum_path, class: "btn green medium" %>	
		<div class="clear"></div>
		<table>
			<tr>
				<th width="20%">Title</th>
				<th width="50%">Description</th>
			</tr>
			<% @forums.each do |forum| %>
			<tr>
				<td><h3><%= forum.title %></h3></td>
				<td class="excerpt"><p><%= forum.description %></p></td>
				<td class="actions">
					<%= link_to("Edit", edit_forum_path(:id => forum.id)) %> |
					<%= link_to 'Delete', forum_path(:id => forum.id), method: :delete, data: {confirm: "Are you sure you want to delete \"#{forum.title}\"?"} %>
				</td>
			</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/admin_dashboard/index.html.erb
<%= render partial: "shared/ggleanalyticsapi" %>
<div id="dashboardWall">
	<div class="grid">
		<section class="chart box">
			<div id="embed-api-auth-container"></div>
<div id="chart-container"></div>
<div id="view-selector-container"></div>
		</section>
		<section class="latest_posts box">
			<h3>3 Latest posts</h3>
			<div class="right">
				<%= link_to "All posts", administrator_posts_path, class: "btn blue medium" %>
			</div>
			<div class="clear"></div>
			<ul>
				<% @posts.first(3).each do |post| %>
					<li>
						<h4><%= link_to post.title, controller: "posts", action: "show", id: post.slug %></h4>
						<p><%= raw strip_tags(post.content).truncate(240) %></p>
					</li>
				<% end %>
			</ul>
		</section>
		<section class="latest_subscribers box">
			<h3>10 Latest subscribers</h3>
			<div class="right">
				<%= link_to "See all", administrator_users_path, class: "btn medium blue" %>
			</div>
			<div class="clear"></div>
			<table>
				<% @users.first(10).each do |user| %>
					<tr>
						<td width="70%">
							<%= user.name %> <%= user.surname %>
							<% if user.country.blank? == false %>
							 from <%= user.country %>
							<% end %>
						</td>					
						<td width="30%" class="reg_date"><%= user.created_at.strftime("On %d %h %Y") %></td>
					</tr>
				<% end %>
			</table>
		</section>
		<section class="latest_topics box">
			<h3>5 Latest topics</h3>
			<div class="right">
				<%= link_to "See all topics", forums_path, class: "btn medium blue" %>
			</div>
			<div class="clear"></div>
			<table>
				<% @topics.first(5).each do |topic| %>
					<tr>
						<td width="70%">
							<h4><%= link_to topic.title, forum_topic_path(id: topic.id, forum_id: topic.forum_id) %></h4>
							<p><%= raw strip_tags(topic.content).truncate(60) %></p>
						</td>					
						<td width="30%" class="reg_date"><%= topic.created_at.strftime("On %d %h %Y") %></td>
					</tr>
				<% end %>
			</table>
		</section>
	</div>
</div>

app/views/admin_dashboard/posts.html.erb
<div id="adminPosts">
	<div class="centralized">
		<h2>Showing all posts</h2>
		<%= link_to "Write a post", administrator_posts_new_path, class: "btn green medium" %>	
		<div class="clear"></div>
		<table>
			<tr>
				<th width="20%">Title</th>
				<th width="50%">Content</th>
				<th width="15%">Author</th>
				<th width="15%">Actions</th>
			</tr>
			<% @posts.each do |post| %>
			<tr>
				<td><h3><%= post.title %></h3></td>
				<td class="excerpt"><p><%= strip_tags(post.content.truncate(400)) %></p></td>
				<td><%= post.user.name %> <%= post.user.surname %></td>
				<td class="actions">
					<%= link_to("Show", controller: "posts", action: "show", id: post.slug) %> | <%= link_to("Edit", administrator_posts_edit_path(:id => post.id)) %> |
					<%= link_to 'Delete', administrator_posts_destroy_path(:id => post.id), method: :delete, data: {confirm: "Are you sure you want to delete \"#{post.title}\"?"} %>
				</td>
			</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/admin_dashboard/users.html.erb
<div id="adminPosts">
	<div class="centralized">
		<h2>Showing all users <span class="size"><%= @users.size %></span></h2>
		<%= link_to "Download CSV", administrator_users_path(format: 'csv'), class: "btn green medium" %>
		<%= link_to "Download XLS", administrator_users_path(format: 'xls'), class: "btn green medium" %>
		<div class="clear"></div>
		<table>
			<tr>
				<th>Name</th>
				<th>Email address</th>
				<th>Phone</th>
				<th>Country</th>
				<th>City</th>
			</tr>
			<% @users.each do |user| %>
			<tr>
				<td>
					<h3><%= user.name %> <%= user.surname %></h3>
					<span class="role tooltipable <%= user.role.name %>" data-tooltip-content="<%= user.role.name %>"></span>
				</td>
				<td class="excerpt"><%= user.email %></td>
				<td><%= user.phone %></td>
				<td><%= user.country %></td>
				<td><%= user.city %></td>
				<% if user.role.name != "admin" %>
				<td>
					<%= link_to "Edit", administrator_user_edit_path(id: user.id) %>
					&nbsp;&nbsp;&nbsp;
					<%= link_to "Delete", administrator_user_destroy_path(id: user.id), data: {confirm: "Are you sure you want to delete \"#{user.name} #{user.surname}\"?"}, method: :delete %>
				</td>
				<% end %>
			</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/admin_dashboard/users.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Surname</Data></Cell>
        <Cell><Data ss:Type="String">Country</Data></Cell>
        <Cell><Data ss:Type="String">Phone</Data></Cell>
        <Cell><Data ss:Type="String">Created at</Data></Cell>
      </Row>
    <% @users.each do |user| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= user.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.surname %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= user.country %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= user.phone %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= user.created_at %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>