config/routes.rb
Rails.application.routes.draw do

  post 'subscribtion_list/subscribe' => 'subscribtion_list#subscribe'
  
  match '/get-gstarcad-2016',  to: 'subscribtion_list#landingPage', via: 'get'
  match '/get-cadprofi-mechanical',  to: 'subscribtion_list#landingPageMech', via: 'get'
  match '/get-cadprofi-hvac-and-piping',  to: 'subscribtion_list#landingPageHVAC', via: 'get'

  #Page Errors
  get '/404' => 'errors#not_found'
  get '/500' => 'errors#internal_server_error'

  scope "(:locale)", locale: /uk|au|nz|it/ do
    resources :contact_us_messages
    resources :support_messages    
    resources :forums do
      resources :topics do
        resources :topic_answers
      end
    end
    
    #devise_for :admins
    devise_for :users

    root 'pages#index'

    match '/professional-cad',  to: 'pages#proCad', via: 'get'
    match '/technical-applications',  to: 'pages#techApps', via: 'get'
    match '/about-us',  to: 'pages#aboutUs', via: 'get'
    match '/contact-us',  to: 'contact_us_messages#new', via: 'get'
    match '/technical-applications/cadprofi-mechanical',  to: 'pages#cadprofiMechanical', via: 'get'
    match '/technical-applications/cadprofi-architectural',  to: 'pages#cadprofiArchitectural', via: 'get'
    match '/technical-applications/cadprofi-hvac-and-piping',  to: 'pages#cadprofiHVAC', via: 'get'
    match '/technical-applications/cadprofi-electrical',  to: 'pages#cadprofiElectrical', via: 'get'
    match '/privacy-policy',  to: 'pages#privacyPolicy', via: 'get'
    match '/site-map',  to: 'pages#siteMap', via: 'get'
    match '/users/downloads',  to: 'pages#downloadArea', via: 'get'
    match '/users/dashboard',  to: 'pages#userDashboard', via: 'get'
    match '/posts',  to: 'posts#index', via: 'get'
    match '/administrator/posts/new',  to: 'posts#new', via: 'get'
    match '/posts/create',  to: 'posts#create', via: 'post'
    match '/administrator/dashboard',  to: 'admin_dashboard#index', via: 'get'
    match '/administrator/posts',  to: 'admin_dashboard#posts', via: 'get'
    match '/administrator/users',  to: 'admin_dashboard#users', via: 'get'
    match '/administrator/forums',  to: 'admin_dashboard#forums', via: 'get'
    match '/administrator/posts/edit',  to: 'posts#edit', via: 'get'
    match '/administrator/posts/update',  to: 'posts#update', via: 'post'
    match '/posts/:id',  to: 'posts#show', via: 'get', as: :slug
    match '/administrator/posts/destroy',  to: 'posts#destroy', via: 'delete'
    match '/administrator/users/:id',  to: 'users#destroy', via: 'delete', as: :administrator_user_destroy
    match '/administrator/users/:id',  to: 'users#edit', via: 'get', as: :administrator_user_edit
    match '/administrator/users/:id',  to: 'users#update', via: 'patch', as: :administrator_user_update
    match '/users/downloads/cad-profi',  to: 'download#downloadCADprofi', via: 'get'
    match '/users/downloads/gstar-cad-64',  to: 'download#downloadGCAD64', via: 'get'
    match '/users/downloads/gstar-cad-32',  to: 'download#downloadGCAD32', via: 'get'
    match '/users/downloads/gstar-cad-pdf',  to: 'download#downloadGCADPDF', via: 'get'

    match '/categories',  to: 'categories#index', via: 'get'
    match '/categories/new',  to: 'categories#new', via: 'get'
    match '/categories/post',  to: 'categories#create', via: 'post'
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :forum
	belongs_to :user
	has_many :topic_answers
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @forums = Forum.all()
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    if user_signed_in?
    	@topic = current_user.topics.build(topic_params)
    elsif admin_signed_in?
      @topic = current_admin.topics.build(topic_params)
    end
  	if @topic.save 
      respond_to do |format|
        format.js
      end
  	else
  	  redirect_to('new')
  	end
  end

  def edit
  	@topic = Topic.find(params[:id])
  end

  def update
  	@topic = Topic.find(params[:id])
  	if @topic.update_attributes(topic_params)
  	  render('index')
  	else
  	  render('new')
  	end
  end

  def delete
    @topic = Topic.find(params[:id])
  end

  def destroy
    @topic = Topic.find(params[:id])
    if @topic.destroy
      redirect_to forums_path
    else
      render("show")
    end
  end

  private
  	def topic_params
  		params.require(:topic).permit(:title, :content, :user_id, :forum_id)
  	end
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/views/topics/create.js.erb
var newTopicId = ('<%= @topic.id %>');
var currentUserName = ('<%= current_user.name.truncate(2, omission: ".") %>');
var currentUserSurname = ('<%= current_user.surname %>');

app/views/topics/edit.html.erb
<h1>Forum#edit</h1>
<p>Find me in app/views/forum/edit.html.erb</p>

app/views/topics/edit.js.erb
var currentForumId = '<%= @topic.forum_id %>';
var currentTopicId = '<%= @topic.id %>';
var currentAnswerId = '<%= params[:id] %>';
var isTitle = '<%= params[:title] %>';

if (isTitle){
	//Make content - contenteditable
	$(".main_title").attr("contenteditable", true);
	//Add class contenteditabe
	$(".main_title").addClass("contenteditable");
	//Focus on content
	$(".main_title").focus();
	//Remove the edit button
	$(".title_area").find(".edit").addClass("hide");
	//Show the save button
	$(".title_area").find(".save").addClass("show");
	//Show the close button
	$(".title_area").find(".close").addClass("show");
} else {
	//Make content - contenteditable
	$(".initial").find(".content").attr("contenteditable", true);
	//Add class contenteditabe
	$(".initial").find(".content").addClass("contenteditable");
	//Focus on content
	$(".initial").find(".content").focus();
	//Append the WYSIWYG editor
	$(".initial").append('<div id="wysiwygEditor"><button id="makeBold" onClick="makeBold();"><i class="fa fa-bold"></i></button><button id="makeItalic" onClick="makeItalic();"><i class="fa fa-italic"></i></button><button id="makeHeadline" onClick="makeHeadline();"><i class="fa fa-header"></i></button><button id="makeUnderlined" onClick="makeUnderlined();"><i class="fa fa-underline"></i></button><button id="makeLink" onClick="makeLink();"><i class="fa fa-link"></i></button></div>');
	//Remove the edit button
	$(".initial").find(".edit").addClass("hide");
	//Show the save button
	$(".initial").find(".save").addClass("show");
	//Show the close button
	$(".initial").find(".close").addClass("show");
}

//WYSIWYG
function makeBold(){
	document.execCommand("bold", false, null);
}
function makeItalic(){
	document.execCommand("italic", false, null);
}
function makeUnderlined(){
	document.execCommand("underline", false, null);
}
function makeHeadline(){
	document.execCommand("formatBlock", true, "h4");
}
function makeLink(){
	var linkValue = prompt("Type the url")
	document.execCommand("createLink", false, linkValue);
}

app/views/topics/new.html.erb
<div clss="centralized">
<%= form_for :topic, url: {action: 'create'} do |f| %>
	<%= f.text_field :title, placeholder: 'Topic name' %>
	<%= f.text_area :content, placeholder: 'Message' %>
	<%= f.text_field :forum_id, placeholder: 'Forum' %>
	<%= submit_tag 'Submit' %>
<% end %>
</div>

app/views/topics/new.js.erb
<% if user_signed_in? or admin_signed_in? %>
	$(".forum_container .forum:last-child ul").append("<li class='contenteditable'><h4 contenteditable class='the_title'>Topic title here</h4><div contenteditable class='the_content'>Write your content here ...</div></li>");
	$(".contenteditable h4").focus();
	$(".forum_container > ul").append('<%=j select_tag "Forums", options_from_collection_for_select(@forums, "id", "title") %>');
	$(".forum_container > ul").append("<div class='action'><button class='blue btn post_topic' id='post_topic'>Post topic</button></div>");
	$(".new_topic").fadeOut();
<% else %>
	//Post a Login / Register message if use has not been signed in.
	//Append the message if it wasn't appended already.
	if (!$('.forum_container .outcome').length == 1) {
		$(".forum_container .action").append("<span class='outcome'>Please <%=j link_to 'Login', new_user_session_path %> or <%=j link_to 'Register', new_user_registration_path %> before writing a topic.</span>")
	}
<% end %>

app/views/topics/show.html.erb
<div id="topicWall" class="centralized">
	<div class="title_area">
	<h1 class="main_title"><%= @topic.title %></h1>
		<div class="edit_cont">
		<% if user_signed_in? %>
			<% if @topic.user_id == current_user.id %>
				<%= link_to(edit_forum_topic_path(forum_id: @topic.id, id: @topic.id, title: "true"), class: 'edit', remote: true) do %>
					<i class="fa fa-pencil"></i>
				<% end %>
				<i class="fa fa-floppy-o save title_save"></i>
				<i class="fa fa-times-circle close"></i>
			<% end %>
		<% end %>
		</div>
	</div>
	<ul id="answers">
		<li class='initial'>
			<div class="author">
				<%= @topic.user.name.truncate(2, omission: '.') %> <%= @topic.user.surname %>
			</div>
			<div class="content"><%= @topic.content.html_safe %></div>
			<% if user_signed_in? %>
				<% if @topic.user_id == current_user.id %>
					<%= link_to(edit_forum_topic_path(forum_id: @topic.id, id: @topic.id), class: 'edit', remote: true) do %>
						<i class="fa fa-pencil"></i>
					<% end %>
					<i class="fa fa-floppy-o save content_save"></i>
					<i class="fa fa-times-circle close"></i>
				<% end %>
			<% end %>
			<div class="clear"></div>
		</li>
		<% @topic.topic_answers.each do |answer| %>
		<li id="<%= answer.id %>" class="answer_list">
			<div class="author"><%= answer.user.name.truncate(2, omission: '.') %> <%= answer.user.surname %></div>
			<div class="content"><%= answer.content.html_safe %></div>
			<!-- If User signed in show the edit button and save buttons -->
			<% if user_signed_in? %>
				<% if answer.user_id == current_user.id %>
					<%= link_to(edit_forum_topic_topic_answer_path(topic_id: @topic.id, id: answer.id), class: 'edit', remote: true) do %>
						<i class="fa fa-pencil"></i>
					<% end %>
					<i class="fa fa-floppy-o save"></i>
					<i class="fa fa-times-circle close"></i>
				<% end %>
			<% end %>
			<span class="written"><%= answer.updated_at().strftime('%d %b. at %k:%M') %></span>	
			<div class="clear"></div>		
		</li>
		<% end %>
	</ul>
	<div class="action">
		<%= link_to "Answer", new_forum_topic_topic_answer_path(topic_id: @topic.id), class: "btn blue answer" ,remote: true %>
		<% if user_signed_in? %>
			<% if @topic.user_id == current_user.id %>
				<%= link_to "Delete this topic", forum_topic_path(topic_id: @topic.id), class: "btn empty red delete", method: "delete", data:{confirm: "Are you sure you would like to delete this topic?"} %>
			<% end %>
		<% end %>
	</div>
</div>